/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/automation/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Automation Status */
        get: operations["automation_status_automation_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/automation/nightly-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Nightly Run */
        post: operations["nightly_run_automation_nightly_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/automation/month-rollover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Month Rollover */
        post: operations["month_rollover_automation_month_rollover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/medication": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Medication Events */
        post: operations["log_medication_events_events_medication_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/protein-shake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Protein Shake Event */
        post: operations["log_protein_shake_event_events_protein_shake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/intake": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Intake Event */
        post: operations["log_intake_event_events_intake_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/import-sample": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Sample */
        post: operations["import_sample_events_import_sample_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Habits */
        get: operations["list_habits_habits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habits/seed-defaults": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seed Defaults */
        post: operations["seed_defaults_habits_seed_defaults_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habits/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recompute */
        post: operations["recompute_habits_recompute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/habit-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Habit Entries */
        get: operations["list_habit_entries_habit_entries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/state/month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Month State */
        get: operations["month_state_state_month_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render/month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Render Month */
        post: operations["render_month_render_month_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_render_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/render/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest */
        get: operations["latest_render_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remarkable/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Remarkable Status */
        get: operations["remarkable_status_remarkable_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remarkable/paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Remarkable Paths */
        get: operations["remarkable_paths_remarkable_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remarkable/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Month */
        post: operations["upload_month_remarkable_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remarkable/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Month */
        post: operations["sync_month_remarkable_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/remarkable/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Instructions */
        get: operations["sync_instructions_remarkable_instructions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoop/oauth/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Start Oauth */
        get: operations["start_oauth_whoop_oauth_start_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoop/oauth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Complete Oauth */
        get: operations["complete_oauth_whoop_oauth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoop/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Whoop Status */
        get: operations["whoop_status_whoop_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoop/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Whoop */
        post: operations["sync_whoop_whoop_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dayone/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dayone Status */
        get: operations["dayone_status_dayone_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dayone/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Dayone */
        post: operations["sync_dayone_dayone_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pipeline/month": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Month Pipeline */
        post: operations["run_month_pipeline_pipeline_month_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Habit
         * @description A habit the system tracks. `kind` controls whether the rule engine
         *     attempts to evaluate it from source events (auto) or only honours manual
         *     overrides (manual).
         *
         *     `metric_only` habits are still computed and stored (so their data stays
         *     available), but they are not user-controlled checkboxes. The renderer shows
         *     them as context metrics (e.g. sleep duration, recovery score next to the
         *     date) rather than as habit cards in the grid or tally. Use this for signals
         *     that reflect the body's state rather than a deliberate action.
         */
        Habit: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Short */
            short: string;
            /**
             * Kind
             * @default auto
             * @enum {string}
             */
            kind: "auto" | "manual";
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Metric Only
             * @default false
             */
            metric_only: boolean;
            /**
             * Sort Order
             * @default 100
             */
            sort_order: number;
            /**
             * Description
             * @default
             */
            description: string;
            /** Event Types */
            event_types?: ("workout" | "sleep" | "recovery" | "meditation" | "deep_work" | "journal" | "manual" | "medication" | "protein_shake" | "intake")[];
            /** Sources */
            sources?: ("whoop" | "muse" | "apple_health" | "manual" | "calendar" | "github" | "remarkable" | "day_one" | "medication")[];
        };
        /**
         * HabitEntry
         * @description The resolved state of one habit on one date, ready to render.
         */
        HabitEntry: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Habit Key */
            habit_key: string;
            /**
             * Status
             * @enum {string}
             */
            status: "checked" | "partial" | "warning" | "missed" | "manual";
            /**
             * Source
             * @enum {string}
             */
            source: "whoop" | "muse" | "apple_health" | "manual" | "calendar" | "github" | "remarkable" | "day_one" | "medication";
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
            /** Linked Source Event Ids */
            linked_source_event_ids?: string[];
            /**
             * Explanation
             * @default
             */
            explanation: string;
            /**
             * Manually Overridden
             * @default false
             */
            manually_overridden: boolean;
        };
        /** IntakeItemInput */
        IntakeItemInput: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Brand Key
             * @default
             */
            brand_key: string;
            /**
             * Brand Label
             * @default
             */
            brand_label: string;
            /**
             * Product Key
             * @default
             */
            product_key: string;
            /**
             * Product Label
             * @default
             */
            product_label: string;
            /**
             * Ingredient Key
             * @default
             */
            ingredient_key: string;
            /**
             * Ingredient Label
             * @default
             */
            ingredient_label: string;
            /**
             * Category
             * @default other
             * @enum {string}
             */
            category: "adaptogen" | "amino_acid" | "base" | "cacao" | "coffee" | "collagen" | "dairy" | "drink" | "fat" | "fiber" | "flavor" | "hormone" | "mineral" | "mushroom" | "nootropic" | "probiotic" | "stimulant" | "substance" | "supplement" | "sweetener" | "other";
            /** Amount */
            amount?: number | null;
            /**
             * Unit
             * @default
             */
            unit: string;
            /** Caffeine Mg */
            caffeine_mg?: number | null;
            /**
             * Time Of Day
             * @default unknown
             * @enum {string}
             */
            time_of_day: "morning" | "afternoon" | "evening" | "night" | "unknown";
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** IntakeLogInput */
        IntakeLogInput: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /** Items */
            items: components["schemas"]["IntakeItemInput"][];
        };
        /**
         * MedicationDayDose
         * @description One day's observed dose count for one medication/supplement.
         */
        MedicationDayDose: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Med Key */
            med_key: string;
            /**
             * Taken
             * @default 0
             */
            taken: number;
            /** Total */
            total?: number | null;
            /** Status */
            status?: ("taken" | "partial" | "missed" | "none") | null;
        };
        /** MedicationDoseInput */
        MedicationDoseInput: {
            /** Med Key */
            med_key: string;
            /** Med Label */
            med_label: string;
            /** Taken Count */
            taken_count: number;
            /** Scheduled Count */
            scheduled_count: number;
            /**
             * Prn
             * @default false
             */
            prn: boolean;
        };
        /**
         * MedicationGroup
         * @description A time-of-day bucket for the medication schedule shown in the PDF.
         */
        MedicationGroup: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Meds */
            meds?: components["schemas"]["MedicationItem"][];
        };
        /**
         * MedicationItem
         * @description A medication or supplement in the renderer schedule.
         *
         *     This is schedule/display metadata, not medical advice. Historical dose logs
         *     stay in ``SourceEvent`` records so the regimen can change without rewriting
         *     old adherence data.
         */
        MedicationItem: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Short */
            short: string;
            /**
             * Dose
             * @default
             */
            dose: string;
            /**
             * Total
             * @default 1
             */
            total: number;
            /**
             * Prn
             * @default false
             */
            prn: boolean;
        };
        /** MedicationLogInput */
        MedicationLogInput: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /** Doses */
            doses: components["schemas"]["MedicationDoseInput"][];
        };
        /**
         * MonthHabitState
         * @description Everything the renderer needs to produce a monthly PDF.
         */
        MonthHabitState: {
            /** Month */
            month: string;
            /** Habits */
            habits: components["schemas"]["Habit"][];
            /** Entries */
            entries: components["schemas"]["HabitEntry"][];
            /** Medication Groups */
            medication_groups?: components["schemas"]["MedicationGroup"][];
            /** Medication Days */
            medication_days?: components["schemas"]["MedicationDayDose"][];
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
        };
        /** ProteinShakeLogInput */
        ProteinShakeLogInput: {
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /**
         * RenderJob
         * @description Audit-trail entry for one PDF render. The repo assigns `id` after insert.
         */
        RenderJob: {
            /** Id */
            id?: string | null;
            /** Month */
            month: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /**
             * Requested At
             * Format: date-time
             */
            requested_at?: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Output Path */
            output_path?: string | null;
            /**
             * Ruleset Version
             * @default v1
             */
            ruleset_version: string;
            /**
             * Triggered By
             * @default manual
             * @enum {string}
             */
            triggered_by: "manual" | "schedule" | "webhook";
            /** Error */
            error?: string | null;
        };
        /** SeedDefaultsResponse */
        SeedDefaultsResponse: {
            /** Seeded */
            seeded: number;
            /** Total Active */
            total_active: number;
            /**
             * Retired
             * @default []
             */
            retired: string[];
            /** Message */
            message: string;
        };
        /**
         * SourceAccount
         * @description An OAuth-connected source (WHOOP, Muse, ...).
         *
         *     Tokens are stored as opaque `bytes` so a future encryption layer can wrap
         *     them without schema changes. Encryption itself is deferred — see
         *     CLAUDE.md §10 and docs/persistence.md.
         */
        SourceAccount: {
            /** Id */
            id?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "whoop" | "muse" | "apple_health" | "manual" | "calendar" | "github" | "remarkable" | "day_one" | "medication";
            /** External User Id */
            external_user_id: string;
            /**
             * Display Name
             * @default
             */
            display_name: string;
            /** Scopes */
            scopes?: string[];
            /** Encrypted Access Token */
            encrypted_access_token?: string | null;
            /** Encrypted Refresh Token */
            encrypted_refresh_token?: string | null;
            /** Token Expires At */
            token_expires_at?: string | null;
            /**
             * Connected At
             * Format: date-time
             */
            connected_at?: string;
            /** Last Sync At */
            last_sync_at?: string | null;
            /** Last Webhook At */
            last_webhook_at?: string | null;
            /**
             * Status
             * @default active
             * @enum {string}
             */
            status: "active" | "revoked" | "expired";
        };
        /**
         * SourceEvent
         * @description A normalized event from a connector or manual import.
         *
         *     `local_date` is precomputed at ingestion time so the rule engine can group
         *     events without needing timezone math.
         */
        SourceEvent: {
            /** Id */
            id: string;
            /**
             * Source
             * @enum {string}
             */
            source: "whoop" | "muse" | "apple_health" | "manual" | "calendar" | "github" | "remarkable" | "day_one" | "medication";
            /** Source Event Id */
            source_event_id: string;
            /**
             * Event Type
             * @enum {string}
             */
            event_type: "workout" | "sleep" | "recovery" | "meditation" | "deep_work" | "journal" | "manual" | "medication" | "protein_shake" | "intake";
            /**
             * Start Time Utc
             * Format: date-time
             */
            start_time_utc: string;
            /** End Time Utc */
            end_time_utc?: string | null;
            /**
             * Local Date
             * Format: date
             */
            local_date: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            /** Metrics */
            metrics?: {
                [key: string]: unknown;
            };
            /** Raw Payload */
            raw_payload?: {
                [key: string]: unknown;
            };
        };
        /** SyncResult */
        SyncResult: {
            /** Adapter */
            adapter: string;
            /**
             * Action
             * @enum {string}
             */
            action: "upload" | "update" | "list";
            /** Dry Run */
            dry_run: boolean;
            /** Target Path */
            target_path: string;
            /**
             * Status
             * @enum {string}
             */
            status: "not_configured" | "manual_required" | "uploaded" | "updated" | "unsupported" | "planned" | "failed";
            /** Message */
            message: string;
            /** Local Pdf Path */
            local_pdf_path?: string | null;
            /**
             * Device Mutated
             * @default false
             */
            device_mutated: boolean;
            /** Instructions */
            instructions?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    status_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    automation_status_automation_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    nightly_run_automation_nightly_run_post: {
        parameters: {
            query?: {
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    month_rollover_automation_month_rollover_post: {
        parameters: {
            query: {
                from_month: string;
                to_month: string;
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_events_events_get: {
        parameters: {
            query?: {
                month?: string | null;
                source?: string | null;
                event_type?: string | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_medication_events_events_medication_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MedicationLogInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_protein_shake_event_events_protein_shake_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProteinShakeLogInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_intake_event_events_intake_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IntakeLogInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_sample_events_import_sample_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_habits_habits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Habit"][];
                };
            };
        };
    };
    seed_defaults_habits_seed_defaults_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SeedDefaultsResponse"];
                };
            };
        };
    };
    recompute_habits_recompute_post: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_habit_entries_habit_entries_get: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HabitEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    month_state_state_month_get: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthHabitState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    render_month_render_month_post: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_render_jobs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderJob"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_render_latest_get: {
        parameters: {
            query?: {
                month?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RenderJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remarkable_status_remarkable_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    remarkable_paths_remarkable_paths_get: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_month_remarkable_upload_post: {
        parameters: {
            query: {
                month: string;
                dry_run?: boolean;
                update?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_month_remarkable_sync_post: {
        parameters: {
            query: {
                month: string;
                dry_run?: boolean;
                update?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_instructions_remarkable_instructions_get: {
        parameters: {
            query: {
                month: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_oauth_whoop_oauth_start_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    complete_oauth_whoop_oauth_callback_get: {
        parameters: {
            query: {
                code: string;
                state: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAccount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    whoop_status_whoop_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sync_whoop_whoop_sync_post: {
        parameters: {
            query: {
                external_user_id: string;
                start: string;
                end: string;
                recompute?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dayone_status_dayone_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    sync_dayone_dayone_sync_post: {
        parameters: {
            query: {
                start: string;
                end: string;
                recompute?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_month_pipeline_pipeline_month_post: {
        parameters: {
            query: {
                external_user_id: string;
                start: string;
                end: string;
                month: string;
                upload?: boolean;
                dry_run?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
